In [4]:
import os
import pandas
data = pandas.read_json("095 supermarkets.json")

In [5]:
data

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [6]:
os.listdir()

['.DS_Store',
 'Untitled.ipynb',
 'Testing.ipynb',
 '095 supermarkets.json',
 '.ipynb_checkpoints']

In [7]:
data.set_index("ID")

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [8]:
data1 = pandas.read_csv("https://pythonhow.com/supermarkets.csv")

In [9]:
data1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [11]:
data1 = set_index("Address")
data1.set_index("Address")
data1

NameError: name 'set_index' is not defined

In [12]:
data1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [13]:
data1.help

AttributeError: 'DataFrame' object has no attribute 'help'

In [14]:
data1 = data1.set_index("Address")
data1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [15]:
data1.loc("332 Hill St","Country")

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [23]:
data1.loc["332 Hill St":"551 Alvarado St","Name":"Employees"]

Name  Employees
Address                                
332 Hill St      Super River         25
3995 23rd St      Ben's Shop         10
1056 Sanchez St      Sanchez         12
551 Alvarado St   Richvalley         20

In [28]:
list(data1.loc[:,"Country"])

['USA', 'USA', 'USA', 'USA', 'USA', 'USA']

In [29]:
data1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [35]:
data1.iloc[1,0:3]

ID                   2
City     San Francisco
State         CA 94119
Name: 735 Dolores St, dtype: object

In [36]:
data.ix[5, "Name"]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


'Richvalley'

In [39]:
data1.loc[3,"Name"]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [3] of <class 'int'>

In [1]:
data1

NameError: name 'data1' is not defined

In [2]:
data1 = pandas.read_csv("https://pythonhow.com/supermarkets.csv")

NameError: name 'pandas' is not defined

In [3]:
import os
import pandas as pd
data = pandas.read_json("095 supermarkets.json")

In [4]:
data

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [5]:
data.set_index("Address")

City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114

In [16]:
data.drop(['City'], axis = 1)


KeyError: "['City'] not found in axis"

In [17]:
import pandas as pd

In [25]:
data=data.drop('2',0)

KeyError: "['2'] not found in axis"

In [32]:
data.drop("332 Hill St", 0)

Country  Employees  ID         Name       State
Address                                                        
3666 21st St        USA          8   1      Madeira    CA 94114
735 Dolores St      USA         15   2  Bready Shop    CA 94119
3995 23rd St        USA         10   4   Ben's Shop    CA 94114
1056 Sanchez St     USA         12   5      Sanchez  California
551 Alvarado St     USA         20   6   Richvalley    CA 94114

In [43]:
data['Continents']=data.shape[0]*['North Americas']

In [44]:
data

Country  Employees  ID         Name             State  \
Address                                                                 
3666 21st St        USA          8   1      Madeira          CA 94114   
735 Dolores St      USA         15   2  Bready Shop          CA 94119   
332 Hill St         USA         25   3  Super River  California 94114   
3995 23rd St        USA         10   4   Ben's Shop          CA 94114   
1056 Sanchez St     USA         12   5      Sanchez        California   
551 Alvarado St     USA         20   6   Richvalley          CA 94114   

                     Continents  
Address                          
3666 21st St     North Americas  
735 Dolores St   North Americas  
332 Hill St      North Americas  
3995 23rd St     North Americas  
1056 Sanchez St  North Americas  
551 Alvarado St  North Americas

In [47]:
data.drop("Continents", 1)

Country  Employees  ID         Name             State
Address                                                              
3666 21st St        USA          8   1      Madeira          CA 94114
735 Dolores St      USA         15   2  Bready Shop          CA 94119
332 Hill St         USA         25   3  Super River  California 94114
3995 23rd St        USA         10   4   Ben's Shop          CA 94114
1056 Sanchez St     USA         12   5      Sanchez        California
551 Alvarado St     USA         20   6   Richvalley          CA 94114

In [66]:
data['Continents']=data["Country"]+","+data["State"]

In [67]:
data

Country  Employees  ID         Name             State  \
Address                                                                 
3666 21st St        USA          8   1      Madeira          CA 94114   
735 Dolores St      USA         15   2  Bready Shop          CA 94119   
332 Hill St         USA         25   3  Super River  California 94114   
3995 23rd St        USA         10   4   Ben's Shop          CA 94114   
1056 Sanchez St     USA         12   5      Sanchez        California   
551 Alvarado St     USA         20   6   Richvalley          CA 94114   

                           Continents  
Address                                
3666 21st St             USA,CA 94114  
735 Dolores St           USA,CA 94119  
332 Hill St      USA,California 94114  
3995 23rd St             USA,CA 94114  
1056 Sanchez St        USA,California  
551 Alvarado St          USA,CA 94114

In [68]:
dataT = data.T

In [69]:
dataT

Address     3666 21st St 735 Dolores St           332 Hill St  3995 23rd St  \
Country              USA            USA                   USA           USA   
Employees              8             15                    25            10   
ID                     1              2                     3             4   
Name             Madeira    Bready Shop           Super River    Ben's Shop   
State           CA 94114       CA 94119      California 94114      CA 94114   
Continents  USA,CA 94114   USA,CA 94119  USA,California 94114  USA,CA 94114   

Address    1056 Sanchez St 551 Alvarado St  
Country                USA             USA  
Employees               12              20  
ID                       5               6  
Name               Sanchez      Richvalley  
State           California        CA 94114  
Continents  USA,California    USA,CA 94114

In [71]:
dataT['144 Gill'] = ['United Kingdom','30','7','Lexo','Westland','UK,Europe']

In [73]:
data = dataT.T

In [75]:
data

Country Employees ID         Name             State  \
Address                                                                       
3666 21st St                USA         8  1      Madeira          CA 94114   
735 Dolores St              USA        15  2  Bready Shop          CA 94119   
332 Hill St                 USA        25  3  Super River  California 94114   
3995 23rd St                USA        10  4   Ben's Shop          CA 94114   
1056 Sanchez St             USA        12  5      Sanchez        California   
551 Alvarado St             USA        20  6   Richvalley          CA 94114   
144 Gill         United Kingdom        30  7         Lexo          Westland   

                           Continents  
Address                                
3666 21st St             USA,CA 94114  
735 Dolores St           USA,CA 94119  
332 Hill St      USA,California 94114  
3995 23rd St             USA,CA 94114  
1056 Sanchez St        USA,California  
551 Alvarado St          USA,CA 94114  
144 Gill                    UK,Europe

In [1]:
from geopy.geocoders import Nominatim

In [6]:
nom = Nominatim(scheme = "http")

In [9]:
nom.geocode("3995 23rd St, San Francisco, CA 94114")

Location(3995, 23rd Street, Noe Valley, SF, California, 94114, USA, (37.7529648, -122.4317141, 0.0))

In [21]:
import os
import pandas as pd

In [20]:
df = pandas.read_csv("https://pythonhow.com/supermarkets.csv")

In [22]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [23]:
df['Address'] = df['Address']+','+df['City']+','+df['State']+','+df['Country']

In [24]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [27]:
df['Cordinates']=df['Address'].apply(nom.geocode)

In [29]:
from geopy.geocoders import Nominatim

In [30]:
nom = Nominatim(scheme = "http")

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


In [31]:
df['Cordinates']=df['Address'].apply(nom.geocode)

In [38]:
df.Cordinates[0]

Location(3666, 21st Street, Noe Valley, SF, California, 94114, USA, (37.756488877551, -122.429343346939, 0.0))

In [42]:
df['latitude']= df['Cordinates'].apply(lambda x: x.latitude)

In [44]:
df['longitude']= df['Cordinates'].apply(lambda y: y.longitude)

In [45]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                          Cordinates   latitude   longitude  
0  (3666, 21st Street, Noe Valley, SF, California...  37.756489 -122.429343  
1  (735, Dolores Street, Liberty Street Historic ...  37.757726 -122.425529  
2  (332, Hill Street, Noe Valley, SF, California,...  37.755725 -122.428601  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  37.752146 -122.429815  
5  (551, Alvarado Street, Noe Valley, SF, Califor...  37.753673 -122.433220

In [1]:
import cv2

In [2]:
img = cv2.imread("100 smallgray.png",0)

In [3]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
img[0:2,3:]

array([[121, 143],
       [255, 147]], dtype=uint8)

In [5]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [19]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [20]:
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [21]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [23]:
import numpy

In [24]:
ims= numpy.hstack((img,img))

In [25]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [26]:
imv = numpy.vstack((img,img))


In [27]:
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [41]:
lsi = numpy.vsplit(imv,3)

In [42]:
lsi

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]